In [16]:
import numpy as np
import pandas as pd

def distance(a,b):
       
    #distance=1-np.dot(a,b)/np.sqrt(np.dot(a,a)*np.dot(b,b))
    return abs(a-b)

def Similarity(Id1, Id2):
    a = df.iloc[Id1]
    b = df.iloc[Id2]
    extra=0
    genre=0
    if a['artists']==b['artists']:
        return 1000;
    if abs(a['year']-b['year'])>10:
        extra=extra+100
    for i in a['genres']:
        if i in b['genres']:
            genre = genre+1
    if genre == 0:
        extra = extra+100
    
    aA = a['acousticness']
    aB = b['acousticness']
    aDistance = distance(aA, aB)
    
    bA = a['danceability']
    bB = b['danceability']
    bDistance = distance(bA, bB)
    
    cA = a['energy']
    cB = b['energy']
    cDistance = distance(cA, cB)
    
    dA = a['instrumentalness']
    dB = b['instrumentalness']
    dDistance = distance(dA, dB)
    
    eA = a['key']
    eB = b['key']
    eDistance = distance(eA, eB)
    
    fA = a['liveness']
    fB = b['liveness']
    fDistance = distance(fA, fB)
    
    gA = a['loudness']
    gB = b['loudness']
    gDistance = distance(gA, gB)
    
    hA = a['popularity']
    hB = b['popularity']
    hDistance = distance(hA, hB)
    
    iA = a['speechiness']
    iB = b['speechiness']
    iDistance = distance(iA, iB)
    
    jA = a['tempo']
    jB = b['tempo']
    jDistance = distance(jA, jB)
    
    kA = a['valence']
    kB = b['valence']
    kDistance = distance(kA, kB)
    return extra+aDistance+bDistance+cDistance+dDistance+eDistance+fDistance+gDistance+hDistance+iDistance+jDistance+kDistance
    #return (-0.59*aDistance)+(0.22*bDistance)+(0.5*cDistance)+(-0.3*dDistance)+(0.011*eDistance)+(-0.075*fDistance)+(0.47*gDistance)+hDistance+(-0.14*iDistance)+(0.14*jDistance)+(0.0093*kDistance)

In [17]:
df = pd.read_csv('onewayoranothernew.csv')
df = df.drop(['Unnamed: 0','playcount','userid'],axis=1)
df = df.drop_duplicates()
df = df.reset_index(drop=True)

In [26]:
df[df['name']=='Lose You To Love Me Selena Gomez']

,acousticness,name,danceability,tempo,loudness,energy,id,instrumentalness,key,liveness,popularity,speechiness,valence,year,artists,genres
118538,0.556,Lose You To Love Me Selena Gomez,0.488,0.002063,-0.001716,0.343,4l0Mvzj72xxOpRrp6h8nHi,0.0,4.0,0.21,85.0,0.0436,0.0978,2020.0,Selena Gomez,"['dance pop', 'pop', 'post-teen pop']"

In [27]:
query_index1=  118538 ##np.random.choice(df.shape[0])
print(df.iloc[query_index1]['name'])

Lose You To Love Me Selena Gomez

In [28]:
simdict = []
for i in range(0, df.shape[0]):
    simdict.append((df.iloc[i]['name'],abs(Similarity(query_index1,i))))

In [29]:
new = pd.DataFrame.from_dict(simdict)
new.columns = ["name","score"]

In [30]:
new=new.sort_values('score')
new.head(11)

                                          name     score
87178                    Bruises Lewis Capaldi  0.984689
130450                Surrender Natalie Taylor  1.769723
129277            No Time To Die Billie Eilish  1.786006
80344   The Less I Know The Better Tame Impala  1.846898
86952            SLOW DANCING IN THE DARK Joji  2.404250
82698                    Photograph Ed Sheeran  2.432453
102337      Level of Concern Twenty One Pilots  2.481449
87177              Before You Go Lewis Capaldi  2.530370
129259                ocean eyes Billie Eilish  2.535599
129301                    Falling Harry Styles  2.611920
102612                     No Idea Don Toliver  2.828608