In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('data_w_artists.csv')

In [3]:
df.head(2)

,acousticness,artists,danceability,duration_ms,energy,explicit,id,instrumentalness,key,liveness,loudness,mode,name,popularity,release_date,speechiness,tempo,valence,year
0,0.995,['Carl Woitschach'],0.708,158648,0.1950,0,6KbQ3uYMLKb5jDxLF7wYDD,0.563,10,0.1510,-12.428,1,Singende Bataillone 1. Teil,0,1928,0.0506,118.469,0.7790,1928
1,0.994,"['Robert Schumann', 'Vladimir Horowitz']",0.379,282133,0.0135,0,6KuQTIu1KoTTkLXKrwlLPV,0.901,8,0.0763,-28.454,1,"Fantasiestücke, Op. 111: Più tosto lento",0,1928,0.0462,83.972,0.0767,1928

In [4]:
df["artists"] = df["artists"].apply(eval)

In [5]:
tags = df['artists'].apply(pd.Series)

In [6]:
tags

,0,1,2,3,4,5,6,7,8,9,...,30,31,32,33,34,35,36,37,38,39
0,Carl Woitschach,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Robert Schumann,Vladimir Horowitz,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Seweryn Goszczyński,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Francisco Canaro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Frédéric Chopin,Vladimir Horowitz,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169904,DripReport,Tyga,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169905,Leon Bridges,Terrace Martin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169906,Kygo,Oh Wonder,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169907,Cash Cash,Andy Grammer,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169908,Ingrid Andress,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
tags = tags.rename(columns = lambda x : 'tag_' + str(x))

In [8]:
tags = tags[['tag_0','tag_1']]

In [9]:
dff =pd.concat([df[:], tags[:]], axis=1)

In [10]:
dff.head(1)

,acousticness,artists,danceability,duration_ms,energy,explicit,id,instrumentalness,key,liveness,...,mode,name,popularity,release_date,speechiness,tempo,valence,year,tag_0,tag_1
0,0.995,[Carl Woitschach],0.708,158648,0.195,0,6KbQ3uYMLKb5jDxLF7wYDD,0.563,10,0.151,...,1,Singende Bataillone 1. Teil,0,1928,0.0506,118.469,0.779,1928,Carl Woitschach,NaN

In [11]:
tags = tags.rename(columns = {'tag_0': 'artists'})
dff = dff.drop(['tag_1'],axis=1)

In [12]:
dff = dff[['id','tag_0']]
dff = dff.rename(columns={'tag_0': 'artistind'})

In [13]:
dff.shape

(169909, 2)

In [14]:
dff.head(1)

                       id        artistind
0  6KbQ3uYMLKb5jDxLF7wYDD  Carl Woitschach

In [15]:
dwg = pd.read_csv("data_w_genres.csv")

In [16]:
dwg=dwg[['artists','genres']]

In [17]:
dwg = dwg.merge(dff, left_on ='artists',right_on='artistind')

In [18]:
dwg.head(1)

,artists,genres,id,artistind
0,"""Test for Victor Young""",[],6ivMXI6YMOPvsiUyTDIV7b,"""Test for Victor Young"""

In [19]:
dwg = dwg.drop(['artistind'],axis=1)

In [20]:
dwg.head(1)

                   artists genres                      id
0  "Test for Victor Young"     []  6ivMXI6YMOPvsiUyTDIV7b

In [21]:
df1 = pd.read_csv('data.csv')

In [22]:
df1=df1.merge(dwg)

In [23]:
df1.to_csv("something.csv")

In [24]:
df1.head()

,acousticness,artist_name,danceability,duration_ms,energy,explicit,id,instrumentalness,key,liveness,...,mode,title,popularity,release_date,speechiness,tempo,valence,year,artists,genres
0,0.995,Carl Woitschach,0.708,158648,0.1950,0,6KbQ3uYMLKb5jDxLF7wYDD,0.563,10,0.1510,...,1,Singende Bataillone 1. Teil,0,1928,0.0506,118.469,0.7790,1928,Carl Woitschach,[]
1,0.994,Robert Schumann & Vladimir Horowitz,0.379,282133,0.0135,0,6KuQTIu1KoTTkLXKrwlLPV,0.901,8,0.0763,...,1,"Fantasiestücke, Op. 111: Più tosto lento",0,1928,0.0462,83.972,0.0767,1928,Robert Schumann,"['classical', 'early romantic era']"
2,0.604,Seweryn Goszczyński,0.749,104300,0.2200,0,6L63VW0PibdM1HDSBoqnoM,0.000,5,0.1190,...,0,Chapter 1.18 - Zamek kaniowski,0,1928,0.9290,107.177,0.8800,1928,Seweryn Goszczyński,[]
3,0.995,Francisco Canaro,0.781,180760,0.1300,0,6M94FkXd15sOAOQYRnWPN8,0.887,1,0.1110,...,0,Bebamos Juntos - Instrumental (Remasterizado),0,1928-09-25,0.0926,108.003,0.7200,1928,Francisco Canaro,"['tango', 'vintage tango']"
4,0.990,Frédéric Chopin & Vladimir Horowitz,0.210,687733,0.2040,0,6N6tiFZ9vLTSOIxkj8qKrd,0.908,11,0.0980,...,1,"Polonaise-Fantaisie in A-Flat Major, Op. 61",1,1928,0.0424,62.149,0.0693,1928,Frédéric Chopin,"['classical', 'early romantic era', 'polish cl..."